package com.example.assigmentweek6.ROOM

const val DATABASE_TASK_NAME = "GROUP3-APP-TASK.db"
const val TASK_ITEM_KEY ="TASK_ITEM_KEY"
const val TASK_POSITION_KEY = "TASK_POSITION_KEY"
const val TASK_DELETE_KEY ="TASK_DELETE_KEY"
const val USER_ITEM_KEY ="USER_ITEM_KEY"
const val DATABASE_USER_NAME = "GROUP3-APP-USER.db"